server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    context-path: /
spring:
  profiles: loc
  mvc:
    static-path-pattern: /static/**       #静态资源路径
    view:
      prefix: /html/               #页面资源路径
  servlet:
    multipart:
      max-request-size: 16MB               # 最大请求大小
      max-file-size: 16MB
      enabled: true
  # redis
  redis:
    host: host
    port: port
    password: password

  ################ mysql配置 ########################
  datasource:
    url: url
    username: username
    password: password
    db-name: db-name
    driverClassName: com.mysql.jdbc.Driver
################ mybatis配置 #######################

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*mapper.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0 # 逻辑已删除值(默认为 1)
    #logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    #自定义填充策略接口实现
    #    meta-object-handler: com.zhengqing.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    #    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
    jdbc-type-for-null: 'null'

################ zqservice配置 #######################

zqApiStore:
  # ZQ网关统一上传文件路径（已弃用）
  fileUploadPath: E:\\baby_img

  isAuth: false

  #首页位置
zqMainPage:
  url: http://127.0.0.1:8809

zqServer:
  # 本服务的IP
  ip: 127.0.0.1

zqServerCenter:
  # 注册中心路径
  addr: http://150.158.28.40:8801/service


zqServiceWebSpider:
  # 爬虫服务路径
  addr: http://150.158.28.40:8806/service


zqAuth:
  # 统一权限登录页面
  ssoUrl: http://150.158.28.40:8804/login.html
  # 管理员登录页面
  ssoAdminUrl: http://150.158.28.40:8804/adminLogin.html
  # 统一权限声明进入哪些页面需要登录权限
  needLoginWebUrl: writeblog,updatablog
  # 统一权限声明进入哪些页面需要会员权限
  needMemberWebUrl: niceblog
  # 统一权限声明进入哪些页面需要管理员权限
  needAdminWebUrl: system

zqClient:
  # 服务调用用户名
  userName: zhangqi
  # 服务调用密码
  password: 123456
  # 注册中心所在地址
  centerAddr: http://150.158.28.40:8801/service
  # 统一权限服务地址
  authAddr: http://127.0.0.1:8804/service

  # 索引库位置
lucene:
  indexPath: D:\\index



