server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    context-path: /
spring:
  profiles: dev
  mvc:
    static-path-pattern: /static/**       #静态资源路径
    view:
      prefix: /html/               #页面资源路径
  servlet:
    multipart:
      max-request-size: 16MB               # 最大请求大小
      max-file-size: 16MB
      enabled: true
  # redis
  redis:
    host: host
    port: port
    password: password

  ################ mysql配置 ########################
  datasource:
    url: url
    username: username
    password: password
    db-name: db-name
    driverClassName: com.mysql.jdbc.Driver
################ mybatis配置 #######################

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*mapper.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0 # 逻辑已删除值(默认为 1)
    #logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    #自定义填充策略接口实现
    #    meta-object-handler: com.zhengqing.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    #    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
    jdbc-type-for-null: 'null'

################ zqservice配置 #######################

zqApiStore:
  # ZQ网关统一上传文件路径（已弃用）
  fileUploadPath: /home/file
  isAuth: false

zqServer:
  # 本服务的IP
  ip: 150.158.28.40
  # 服务注册用户名
  userName: zhangqi
  # 服务注册密码
  password: 123456
  # 服务注册是否总是重试，该参数为true时，配置的重试次数将不起作用
  alwaysRetry: false
  # 服务注册重试次数，仅当服务注册alwaysRetry为false时生效
  retryCount: 10
  # 服务注册重试间隔/ms
  retryTime: 10000

zqServerCenter:
  # 注册中心路径
  addr: http://150.158.28.40:8801/service

zqAuth:
  # redis登录用户信息过期时间/s
  redisUserTimeout: 604800
  # 登录用户信息cookie过期时间/s
  cookieUserTimeout: 604800
  # 统一权限登录页面
  ssoUrl: http://150.158.28.40:8804/login.html


zqClient:
  # 服务调用用户名
  userName: zhangqi
  # 服务调用密码
  password: 123456
  # 注册中心所在地址
  centerAddr: http://150.158.28.40:8801/service
  # 统一权限服务地址
  authAddr: http://150.158.28.40:8804/service

# 索引库位置
lucene:
  indexPath: /home/index

# gitee 的 开发者key
# 需要到 https://gitee.com/oauth/applications 去申请
gitee:
  cilent_id: cilent_id
  client_secret: client_secret
  reurl: http://1.15.232.156/oauth?type=gitee

# sms的参数
# sms的参数
sms:
  # 腾讯云账户密钥对
  secretId: secretId
  secretKey: secretKey
  # 指定请求方法
  reqMethod: POST
  # 指定超时时间
  connTimeout: 60
  # 指定域名
  endpoint: sms.tencentcloudapi.com
  # 签名
  signMethod: signMethod
  # 地域信息
  region: region
  # 短信签名内容
  signName: signName
  # 短信应用ID
  sdkAppId: sdkAppId
  # 用户的 session 内容,可以携带用户的sessionID等上下文信息
  sessionContext: session
  # 短信注册模板
  registerTemplateId: registerTemplateId
  # 短信登录模板
  loginTemplateId: loginTemplateId




